#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso cycleIDvars
wmake libso heatExchangerBC
wmake libso magneticProp
wmake libso movingMagnetBC
wmake libso movingMagnetConstMurBC
wmake libso psiCouple
wmake libso psiCoupleConstMur
wmake libso solidMultiRegionControl
wmake libso tempCouple
wmake libso therCycleControl

# ----------------------------------------------------------------- end-of-file
